In [1]:
import os
import sys
import numpy as np
import pandas as pd
from sklearn.feature_selection import mutual_info_regression

sys.path.append(os.path.abspath("../../")) ; from EPF import variables
sys.path.insert(0, "../helpers/"); from run_parrellel import *

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

Inputs

In [2]:
features = pd.read_parquet(variables.FEATURES_DATASET_FOR_SELECTION_PATH)
targets = pd.read_parquet(variables.AGG_TARGET_DATASET_PATH)

display(features[:3])
display(targets[:3])

,nsw_price_asinh_lag_1,nsw_price_asinh_lag_2,nsw_price_asinh_lag_4,nsw_price_asinh_lag_12,nsw_price_asinh_lag_48,nsw_price_asinh_lag_96,nsw_price_asinh_lag_336,nsw_price_asinh_lag_335,nsw_price_asinh_lag_337,nsw_price_asinh_rmean_48,nsw_price_asinh_rmean_336,qld_price_asinh_lag_1,qld_price_asinh_lag_2,qld_price_asinh_lag_4,qld_price_asinh_lag_12,qld_price_asinh_lag_48,qld_price_asinh_lag_96,qld_price_asinh_lag_336,qld_price_asinh_lag_335,qld_price_asinh_lag_337,qld_price_asinh_rmean_48,qld_price_asinh_rmean_336,sa_price_asinh_lag_1,sa_price_asinh_lag_2,sa_price_asinh_lag_4,sa_price_asinh_lag_12,sa_price_asinh_lag_48,sa_price_asinh_lag_96,sa_price_asinh_lag_336,sa_price_asinh_lag_335,sa_price_asinh_lag_337,sa_price_asinh_rmean_48,sa_price_asinh_rmean_336,vic_price_asinh_lag_1,vic_price_asinh_lag_2,vic_price_asinh_lag_4,vic_price_asinh_lag_12,vic_price_asinh_lag_48,vic_price_asinh_lag_96,vic_price_asinh_lag_336,vic_price_asinh_lag_335,vic_price_asinh_lag_337,vic_price_asinh_rmean_48,vic_price_asinh_rmean_336,hour,dayofweek,month,dayofyear,hour_sin,hour_cos,dow_sin,dow_cos,month_sin,month_cos,is_weekend,is_holiday,is_peak,is_shoulder,is_off_peak,is_offday,nsw_price_lag_1,nsw_price_lag_2,nsw_price_lag_3,nsw_price_lag_4,nsw_price_lag_6,nsw_price_lag_8,nsw_price_lag_12,nsw_price_lag_24,nsw_price_lag_26,nsw_price_lag_28,nsw_price_lag_30,nsw_price_lag_32,nsw_price_lag_34,nsw_price_lag_36,nsw_price_lag_38,nsw_price_lag_40,nsw_price_lag_42,nsw_price_lag_44,nsw_price_lag_46,nsw_price_lag_48,nsw_price_lag_49,nsw_price_lag_50,nsw_price_lag_51,nsw_price_lag_52,nsw_price_lag_54,nsw_price_lag_56,nsw_price_lag_58,nsw_price_lag_60,nsw_price_lag_62,nsw_price_lag_64,nsw_price_lag_66,nsw_price_lag_68,nsw_price_lag_70,nsw_price_lag_96,nsw_price_lag_97,nsw_price_lag_98,nsw_price_lag_143,nsw_price_lag_144,nsw_price_lag_145,nsw_price_lag_191,nsw_price_lag_192,nsw_price_lag_193,nsw_price_lag_335,nsw_price_lag_336,nsw_price_lag_337,nsw_price_lag_671,nsw_price_lag_672,nsw_price_lag_673,qld_price_lag_1,qld_price_lag_2,qld_price_lag_3,qld_price_lag_4,qld_price_lag_6,qld_price_lag_8,qld_price_lag_12,qld_price_lag_24,qld_price_lag_26,qld_price_lag_28,qld_price_lag_30,qld_price_lag_32,qld_price_lag_34,qld_price_lag_36,qld_price_lag_38,qld_price_lag_40,qld_price_lag_42,qld_price_lag_44,qld_price_lag_46,qld_price_lag_48,qld_price_lag_49,qld_price_lag_50,qld_price_lag_51,qld_price_lag_52,qld_price_lag_54,qld_price_lag_56,qld_price_lag_58,qld_price_lag_60,qld_price_lag_62,qld_price_lag_64,qld_price_lag_66,qld_price_lag_68,qld_price_lag_70,qld_price_lag_96,qld_price_lag_97,qld_price_lag_98,qld_price_lag_143,qld_price_lag_144,qld_price_lag_145,qld_price_lag_191,qld_price_lag_192,qld_price_lag_193,qld_price_lag_335,qld_price_lag_336,qld_price_lag_337,qld_price_lag_671,qld_price_lag_672,qld_price_lag_673,sa_price_lag_1,sa_price_lag_2,sa_price_lag_3,sa_price_lag_4,sa_price_lag_6,sa_price_lag_8,sa_price_lag_12,sa_price_lag_24,sa_price_lag_26,sa_price_lag_28,sa_price_lag_30,sa_price_lag_32,sa_price_lag_34,sa_price_lag_36,sa_price_lag_38,sa_price_lag_40,sa_price_lag_42,sa_price_lag_44,sa_price_lag_46,sa_price_lag_48,sa_price_lag_49,sa_price_lag_50,sa_price_lag_51,sa_price_lag_52,sa_price_lag_54,sa_price_lag_56,sa_price_lag_58,sa_price_lag_60,sa_price_lag_62,sa_price_lag_64,sa_price_lag_66,sa_price_lag_68,sa_price_lag_70,sa_price_lag_96,sa_price_lag_97,sa_price_lag_98,sa_price_lag_143,sa_price_lag_144,sa_price_lag_145,sa_price_lag_191,sa_price_lag_192,sa_price_lag_193,sa_price_lag_335,sa_price_lag_336,sa_price_lag_337,sa_price_lag_671,sa_price_lag_672,sa_price_lag_673,vic_price_lag_1,vic_price_lag_2,vic_price_lag_3,vic_price_lag_4,vic_price_lag_6,vic_price_lag_8,vic_price_lag_12,vic_price_lag_24,vic_price_lag_26,vic_price_lag_28,vic_price_lag_30,vic_price_lag_32,vic_price_lag_34,vic_price_lag_36,vic_price_lag_38,vic_price_lag_40,vic_price_lag_42,vic_price_lag_44,vic_price_lag_46,vic_price_lag_48,vic_price_lag_49,vic_price_lag_50,vic_price_lag_51,vic_price_lag_52,vic_price_lag_54,vic_price_lag_56,vic_price_lag_58,vic_price_lag_60,vic_price_lag_62,vic_price_lag_64,vic_price_lag_66,vic_price_lag_68,vic_price_lag_70,vic_price_lag_96,vic_price_lag_97,vic_price_lag_98,vic_price_lag_143,vic_price_lag_144,vic_price_lag_145,vic_price_lag_191,vic_price_lag_192,vic_price_lag_193,vic_price_lag_335,vic_price_lag_336,vic_price_lag_337,vic_price_lag_671,vic_price_lag_672,vic_price_lag_673,nsw_price_lag_annual_-2,nsw_price_asinh_lag_annual_-2,nsw_price_lag_annual_-1,nsw_price_asinh_lag_annual_-1,nsw_price_lag_annual_+0,nsw_price_asinh_lag_annual_+0,nsw_price_lag_annual_+1,nsw_price_asinh_lag_annual_+1,nsw_price_lag_annual_+2,nsw_price_asinh_lag_annual_+2,nsw_price_annual_rmean_96,nsw_price_annual_rmax_96,nsw_price_annual_rstd_96,nsw_price_annual_spike_96,nsw_price_yoy_change,nsw_price_yoy_ratio,qld_price_lag_annual_-2,qld_price_asinh_lag_annual_-2,qld_price_lag_annual_-1,qld_price_asinh_lag_annual_-1,qld_price_lag_annual_+0,qld_price_asinh_lag_annual_+0,qld_price_lag_annual_+1,qld_price_asinh_lag_annual_+1,qld_price_lag_annual_+2,qld_price_asinh_lag_annual_+2,qld_price_annual_rmean_96,qld_price_annual_rmax_96,qld_price_annual_rstd_96,qld_price_annual_spike_96,qld_price_yoy_change,qld_price_yoy_ratio,sa_price_lag_annual_-2,sa_price_asinh_lag_annual_-2,sa_price_lag_annual_-1,sa_price_asinh_lag_annual_-1,sa_price_lag_annual_+0,sa_price_asinh_lag_annual_+0,sa_price_lag_annual_+1,sa_price_asinh_lag_annual_+1,sa_price_lag_annual_+2,sa_price_asinh_lag_annual_+2,sa_price_annual_rmean_96,sa_price_annual_rmax_96,sa_price_annual_rstd_96,sa_price_annual_spike_96,sa_price_yoy_change,sa_price_yoy_ratio,vic_price_lag_annual_-2,vic_price_asinh_lag_annual_-2,vic_price_lag_annual_-1,vic_price_asinh_lag_annual_-1,vic_price_lag_annual_+0,vic_price_asinh_lag_annual_+0,vic_price_lag_annual_+1,vic_price_asinh_lag_annual_+1,vic_price_lag_annual_+2,vic_price_asinh_lag_annual_+2,vic_price_annual_rmean_96,vic_price_annual_rmax_96,vic_price_annual_rstd_96,vic_price_annual_spike_96,vic_price_yoy_change,vic_price_yoy_ratio,nsw_price_rmean_4,nsw_price_rstd_4,nsw_price_rmax_4,nsw_price_rmin_4,nsw_price_rmean_8,nsw_price_rstd_8,nsw_price_rmax_8,nsw_price_rmin_8,nsw_price_rmean_24,nsw_price_rstd_24,nsw_price_rmax_24,nsw_price_rmin_24,nsw_price_rmean_48,nsw_price_rstd_48,nsw_price_rmax_48,nsw_price_rmin_48,nsw_price_rmean_96,nsw_price_rstd_96,nsw_price_rmax_96,nsw_price_rmin_96,nsw_price_rmean_336,nsw_price_rstd_336,nsw_price_rmax_336,nsw_price_rmin_336,nsw_price_rmean_672,nsw_price_rstd_672,nsw_price_rmax_672,nsw_price_rmin_672,nsw_price_rmean_2016,nsw_price_rstd_2016,nsw_price_rmax_2016,nsw_price_rmin_2016,qld_price_rmean_4,qld_price_rstd_4,qld_price_rmax_4,qld_price_rmin_4,qld_price_rmean_8,qld_price_rstd_8,qld_price_rmax_8,qld_price_rmin_8,qld_price_rmean_24,qld_price_rstd_24,qld_price_rmax_24,qld_price_rmin_24,qld_price_rmean_48,qld_price_rstd_48,qld_price_rmax_48,qld_price_rmin_48,qld_price_rmean_96,qld_price_rstd_96,qld_price_rmax_96,qld_price_rmin_96,qld_price_rmean_336,qld_price_rstd_336,qld_price_rmax_336,qld_price_rmin_336,qld_price_rmean_672,qld_price_rstd_672,qld_price_rmax_672,qld_price_rmin_672,qld_price_rmean_2016,qld_price_rstd_2016,qld_price_rmax_2016,qld_price_rmin_2016,sa_price_rmean_4,sa_price_rstd_4,sa_price_rmax_4,sa_price_rmin_4,sa_price_rmean_8,sa_price_rstd_8,sa_price_rmax_8,sa_price_rmin_8,sa_price_rmean_24,sa_price_rstd_24,sa_price_rmax_24,sa_price_rmin_24,sa_price_rmean_48,sa_price_rstd_48,sa_price_rmax_48,sa_price_rmin_48,sa_price_rmean_96,sa_price_rstd_96,sa_price_rmax_96,sa_price_rmin_96,sa_price_rmean_336,sa_price_rstd_336,sa_price_rmax_336,sa_price_rmin_336,sa_price_rmean_672,sa_price_rstd_672,sa_price_rmax_672,sa_price_rmin_672,sa_price_rmean_2016,sa_price_rstd_2016,sa_price_rmax_2016,sa_price_rmin_2016,vic_price_rmean_4,vic_price_rstd_4,vic_price_rmax_4,vic_price_rmin_4,vic_price_rmean_8,vic_price_rstd_8,vic_price_rmax_8,vic_price_rmin_8,vic_price_rmean_24,vic_price_rstd_24,vic_price_rmax_24,vic_price_rmin_24,vic_price_rmean_48,vic_price_rstd_48,vic_price_rmax_48,vic_price_rmin_48,vic_price_rmean_96,vic_price_rstd_96,vic_price_rmax_96,vic_price_rmin_96,vic_price_rmean_336,vic_price_rstd_336,vic_price_rmax_336,vic_price_rmin_336,vic_price_rmean_672,vic_price_rstd_672,vic_price_rmax_672,vic_price_rmin_672,vic_price_rmean_2016,vic_price_rstd_2016,vic_price_rmax_2016,vic_price_rmin_2016,nsw_price_spike_flag_48,nsw_price_neg_flag_48,nsw_price_q90_336,nsw_price_q10_336,nsw_price_pct_rank_48,qld_price_spike_flag_48,qld_price_neg_flag_48,qld_price_q90_336,qld_price_q10_336,qld_price_pct_rank_48,sa_price_spike_flag_48,sa_price_neg_flag_48,sa_price_q90_336,sa_price_q10_336,sa_price_pct_rank_48,vic_price_spike_flag_48,vic_price_neg_flag_48,vic_price_q90_336,vic_price_q10_336,vic_price_pct_rank_48,nsw_price_hours_since_spike_150,nsw_price_log1p_hours_since_spike_150,nsw_price_spike_150_last_1h,nsw_price_spike_150_last_6h,nsw_price_spike_150_last_12h,nsw_price_spike_150_last_24h,nsw_price_spike_150_last_48h,nsw_price_spike_150_last_168h,nsw_price_hours_since_spike_300,nsw_price_log1p_hours_since_spike_300,nsw_price_spike_300_last_1h,nsw_price_spike_300_last_6h,nsw_price_spike_300_last_12h,nsw_price_spike_300_last_24h,nsw_price_spike_300_last_48h,nsw_price_spike_300_last_168h,nsw_price_hours_since_spike_1000,nsw_price_log1p_hours_since_spike_1000,nsw_price_spike_1000_last_1h,nsw_price_spike_1000_last_6h,nsw_price_spike_1000_last_12h,nsw_price_spike_1000_last_24h,nsw_price_spike_1000_last_48h,nsw_price_spike_1000_last_168h,nsw_price_hours_since_any_spike,qld_price_hours_since_spike_150,qld_price_log1p_hours_since_spike_150,qld_price_spike_150_last_1h,qld_price_spike_150_last_6h,qld_price_spike_150_last_12h,qld_price_spike_150_last_24h,qld_price_spike_150_last_48h,qld_price_spike_150_last_168h,qld_price_hours_since_spike_300,qld_price_log1p_hours_since_spike_300,qld_price_spike_300_last_1h,qld_price_spike_300_last_6h,qld_price_spike_300_last_12h,qld_price_spike_300_last_24h,qld_price_spike_300_last_48h,qld_price_spike_300_last_168h,qld_price_hours_since_spike_1000,qld_price_log1p_hours_since_spike_1000,qld_price_spike_1000_last_1h,qld_price_spike_1000_last_6h,qld_price_spike_1000_last_12h,qld_price_spike_1000_last_24h,qld_price_spike_1000_last_48h,qld_price_spike_1000_last_168h,qld_price_hours_since_any_spike,sa_price_hours_since_spike_150,sa_price_log1p_hours_since_spike_150,sa_price_spike_150_last_1h,sa_price_spike_150_last_6h,sa_price_spike_150_last_12h,sa_price_spike_150_last_24h,sa_price_spike_150_last_48h,sa_price_spike_150_last_168h,sa_price_hours_since_spike_300,sa_price_log1p_hours_since_spike_300,sa_price_spike_300_last_1h,sa_price_spike_300_last_6h,sa_price_spike_300_last_12h,sa_price_spike_300_last_24h,sa_price_spike_300_last_48h,sa_price_spike_300_last_168h,sa_price_hours_since_spike_1000,sa_price_log1p_hours_since_spike_1000,sa_price_spike_1000_last_1h,sa_price_spike_1000_last_6h,sa_price_spike_1000_last_12h,sa_price_spike_1000_last_24h,sa_price_spike_1000_last_48h,sa_price_spike_1000_last_168h,sa_price_hours_since_any_spike,vic_price_hours_since_spike_150,vic_price_log1p_hours_since_spike_150,vic_price_spike_150_last_1h,vic_price_spike_150_last_6h,vic_price_spike_150_last_12h,vic_price_spike_150_last_24h,vic_price_spike_150_last_48h,vic_price_spike_150_last_168h,vic_price_hours_since_spike_300,vic_price_log1p_hours_since_spike_300,vic_price_spike_300_last_1h,vic_price_spike_300_last_6h,vic_price_spike_300_last_12h,vic_price_spike_300_last_24h,vic_price_spike_300_last_48h,vic_price_spike_300_last_168h,vic_price_hours_since_spike_1000,vic_price_log1p_hours_since_spike_1000,vic_price_spike_1000_last_1h,vic_price_spike_1000_last_6h,vic_price_spike_1000_last_12h,vic_price_spike_1000_last_24h,vic_price_spike_1000_last_48h,vic_price_spike_1000_last_168h,vic_price_hours_since_any_spike,nsw_price_mom_4,nsw_price_mom_12,nsw_price_mom_48,nsw_price_accel_4,nsw_price_accel_12,nsw_price_spike_count_48,nsw_price_spike_count_336,nsw_price_neg_count_48,nsw_price_spike_intensity_48,nsw_price_spike_intensity_336,nsw_price_pct_rank_336,qld_price_mom_4,qld_price_mom_12,qld_price_mom_48,qld_price_accel_4,qld_price_accel_12,qld_price_spike_count_48,qld_price_spike_count_336,qld_price_neg_count_48,qld_price_spike_intensity_48,qld_price_spike_intensity_336,qld_price_pct_rank_336,sa_price_mom_4,sa_price_mom_12,sa_price_mom_48,sa_price_accel_4,sa_price_accel_12,sa_price_spike_count_48,sa_price_spike_count_336,sa_price_neg_count_48,sa_price_spike_intensity_48,sa_price_spike_intensity_336,sa_price_pct_rank_336,vic_price_mom_4,vic_price_mom_12,vic_price_mom_48,vic_price_accel_4,vic_price_accel_12,vic_price_spike_count_48,vic_price_spike_count_336,vic_price_neg_count_48,vic_price_spike_intensity_48,vic_price_spike_intensity_336,vic_price_pct_rank_336,nsw_price_vs_qld_price_spread,nsw_price_vs_qld_price_spread_lag1,nsw_price_vs_sa_price_spread,nsw_price_vs_sa_price_spread_lag1,nsw_price_vs_vic_price_spread,nsw_price_vs_vic_price_spread_lag1,qld_price_vs_nsw_price_spread,qld_price_vs_nsw_price_spread_lag1,qld_price_vs_sa_price_spread,qld_price_vs_sa_price_spread_lag1,qld_price_vs_vic_price_spread,qld_price_vs_vic_price_spread_lag1,sa_price_vs_nsw_price_spread,sa_price_vs_nsw_price_spread_lag1,sa_price_vs_qld_price_spread,sa_price_vs_qld_price_spread_lag1,sa_price_vs_vic_price_spread,sa_price_vs_vic_price_spread_lag1,vic_price_vs_nsw_price_spread,vic_price_vs_nsw_price_spread_lag1,vic_price_vs_qld_price_spread,vic_price_vs_qld_price_spread_lag1,vic_price_vs_sa_price_spread,vic_price_vs_sa_price_spread_lag1,multi_region_spike,region_spike_count
Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2019-01-01 00:00:00,0.639675,0.639675,0.677070,0.681773,0.619326,0.793927,0.983632,0.961297,0.929465,0.724064,0.743680,0.616258,0.620037,0.656875,0.689513,0.651151,0.768203,1.013923,1.013923,0.962055,0.720022,0.709588,0.739926,0.742987,0.767697,0.705104,0.624607,0.854396,1.065745,1.052053,1.006992,0.748316,0.834653,0.703678,0.706802,0.730356,0.694157,0.611476,0.789256,0.957967,0.941149,0.899274,0.735209,0.759103,0,1,1,1,0.0,1.0,0.781832,0.62349,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,68.419991,68.420021,73.000000,73.000000,68.420021,70.995842,73.583099,73.000000,84.972710,80.271431,91.859993,94.800003,91.860062,80.000000,82.461090,84.238937,80.980003,80.979889,79.855591,65.968361,68.889999,68.420021,68.889999,68.889999,63.404652,65.959679,66.298553,64.000000,65.653282,66.417992,65.933502,68.889999,78.868301,88.000000,85.772560,86.985161,91.860008,96.739899,100.743759,73.015747,80.980003,80.980003,111.634438,115.010002,106.919411,94.896080,95.033234,93.555511,65.601181,66.053612,70.302742,70.514374,66.710037,69.989029,74.546257,70.299629,82.960281,77.878464,87.966713,91.420280,89.752953,79.685989,82.710281,84.500031,84.500000,83.985268,84.500000,69.815041,73.405617,84.500000,82.520103,84.500031,67.440117,70.838547,70.750183,67.865059,81.989998,84.500031,84.500000,84.5,84.500031,84.602112,81.989998,81.989998,76.497643,81.137047,84.500053,65.250031,72.851509,70.828072,119.680000,119.680000,111.7481,84.599998,84.720001,84.500000,80.931519,81.325706,85.037308,84.535843,76.500000,76.5,76.5,76.5,86.522163,82.959312,94.814941,99.024307,94.330070,81.400772,82.371292,83.819649,80.580772,78.735191,77.960007,66.602043,70.218658,68.328003,69.357277,69.375427,65.057419,67.299156,68.699837,65.442299,66.448380,65.455513,65.417221,68.003258,76.500000,96.220718,91.194588,96.122864,104.246269,112.006149,116.095169,100.309662,118.501556,116.200104,125.715149,127.926537,118.601883,103.256752,103.250366,102.389557,76.320541,76.713921,79.911072,79.704063,75.040352,75.517021,75.126244,73.786743,84.427483,80.953690,92.042671,95.600533,92.049744,80.312637,81.747276,83.635094,79.973801,79.408607,78.195976,65.029999,67.836090,66.435692,67.379051,67.392662,62.863468,65.029999,65.029999,63.661190,65.029999,65.029999,65.029999,67.930328,77.304138,87.378792,84.033020,86.242241,90.627243,97.363358,101.440819,84.062973,98.792259,96.452789,108.637222,111.136063,102.547653,92.147430,92.130592,91.372009,98.930069,0.873788,65.613129,0.616358,64.984612,0.611095,65.420326,0.614745,61.000000,0.577381,82.727409,167.290054,30.127193,0.0,-2.04908,0.953791,98.626663,0.871629,64.989998,0.611140,64.780022,0.609379,64.780022,0.609379,60.394550,0.572205,84.439903,164.169128,29.127121,0.0,-6.06998,0.892521,91.339996,0.818794,62.543468,0.590512,61.209480,0.579168,61.237228,0.579405,56.352169,0.537294,91.577873,206.009995,40.653492,0.0,17.79192,1.269925,97.010361,0.860075,64.803238,0.609574,63.733761,0.600577,64.108093,0.603731,59.347080,0.563218,90.701073,205.039536,36.866547,0.0,11.49655,1.162150,68.193886,4.117090,73.000000,62.935532,69.922302,3.763838,74.870331,62.935532,74.328758,4.852788,83.386627,62.935532,79.041687,7.715037,104.800003,62.935532,77.361885,8.498634,104.800003,62.935532,81.699005,10.841684,115.010002,62.935532,82.529900,18.095814,295.305145,41.311577,78.109482,37.121918,298.000153,9.163,65.166893,4.797317,70.302742,58.710041,67.383179,4.234723,72.32695,58.710041,73.715530,6.268405,84.600037,58.710041,78.542076,8.096382,102.432533,58.710041,80.636925,7.523528,102.432533,58.710041,77.261642,9.068141,120.715881,58.710041,76.460197,17.143091,291.347076,37.925018,62.774620,30.970716,291.347076,-445.355011,81.573982,2.522381,85.037308,79.001404,81.029457,3.484387,85.037308,76.5,79.492783,3.388058,86.142616,76.5,82.120110,6.702264,108.155899,76.5,79.542503,9.369513,108.155899,64.548714,94.205719,17.309040,230.999802,64.548714,95.460472,21.677629,329.89502,48.290344,91.819229,42.659698,331.903412,9.048305,77.043961,2.011791,79.911072,75.230309,77.324875,2.286518,80.362328,75.040352,77.415726,2.723206,84.505669,74.937019,80.419441,6.299169,104.957062,73.786743,77.421539,8.253745,104.957062,62.863468,83.819603,13.171413,197.679825,62.863468,83.808800,18.353277,290.0,42.716637,83.332191,41.998089,313.135254,8.94949,0.0,0.0,94.800003,68.419998,0.020833,0.0,0.0,86.761383,65.015045,0.020833,0.0,0.0,116.512383,76.5,0.437500,0.0,0.0,98.967484,68.026978,0.208333,186.0,5.231109,0.0,0.0,0.0,0.0,0.0,0.0,336.0,5.820083,0.0,0.0,0.0,0.0,0.0,0.0,336.0,5.820083,0.0,0.0,0.0,0.0,0.0,0.0,186.0,186.0,5.231109,0.0,0.0,0.0,0.0,0.0,0.0,336.0,5.820083,0.0,0.0,0.0,0.0,0.0,0.0,336.0,5.820083,0.0,0.0,0.0,0.0,0.0,0.0,186.0,146.5,4.993828,0.0,0.0,0.0,0.0,0.0,1.0,186.0,5.231109,0.0,0.0,0.0,0.0,0.0,0.0,336.0,5.820083,0.0,0.0,0.0,0.0,0.0,0.0,146.5,146.5,4.993828,0.0,0.0,0.0,0.0,0.0,1.0,336.0,5.820083,0.0,0.0,0.0,0.0,0.0,0.0,336.0,5.820083,0.0,0.0,0.0,0.0,0.0,0.0,146.5,-10.06447,-10.64757,-3.03283,-12.06863,-11.23067,0.0,0.0,0.0,0.0,0.0,0.002976,-11.80433,-15.83622,-11.105000,-12.32967,-20.08285,0.0,0.0,0.0,0.0,0.0,0.002976,-5.53444,2.50140,12.39936,-13.570280,2.50140,0.0,0.0,0.0,0.0,80.999802,0.211310,-4.47375,0.10407,10.20031,-8.66079,-1.23543,0.0,0.0,0.0,0.0,47.679829,0.258929,4.22549,2.81881,-16.06587,-12.51153,-12.29478,-7.90055,-4.22549,-2.81881,-20.291361,-15.330340,-16.520269,-10.719360,16.06587,12.51153,20.291361,15.330340,3.77109,4.61098,12.29478,7.90055,16.520269,10.719360,-3.77109,-4.61098,0.0,0.0

,target_h1,target_h2,target_h3,target_h4,target_h5,target_h6,target_h7,target_h8,target_h9,target_h10,target_h11,target_h12,target_h13,target_h14,target_h15,target_h16,target_h17,target_h18,target_h19,target_h20,target_h21,target_h22,target_h23,target_h24,target_h25,target_h26,target_h27,target_h28,target_h29,target_h30,target_h31,target_h32,target_h33,target_h34,target_h35,target_h36,target_h37,target_h38,target_h39,target_h40,target_h41,target_h42,target_h43,target_h44,target_h45,target_h46,target_h47,target_h48,target_h49,target_h50,target_h51,target_h52,target_h53,target_h54,target_h55,target_h56,target_h57,target_h58,target_h59,target_h60,target_h61,target_h62,target_h63,target_h64,target_h65,target_h66,target_h67,target_h68,target_h69,target_h70,target_h71,target_h72,target_h73,target_h74,target_h75,target_h76,target_h77,target_h78,target_h79,target_h80,target_h81,target_h82,target_h83,target_h84,target_h85,target_h86,target_h87,target_h88,target_h89,target_h90,target_h91,target_h92,target_h93,target_h94,target_h95,target_h96
Date,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2019-01-01 00:00:00,62.935532,68.092598,69.269501,68.270203,68.310501,63.749329,64.000000,71.508797,71.540848,68.420021,68.529953,68.420021,67.531418,68.401917,74.887894,71.274857,74.116692,73.158730,74.930634,74.213852,73.968918,68.420021,69.151901,67.677589,68.419998,66.572327,67.704063,67.904198,68.419968,66.322372,64.939743,66.094231,67.528061,64.000000,61.922749,61.772751,61.889999,61.889999,64.000000,64.000000,61.889999,60.694931,60.709541,48.000000,52.040939,48.990051,48.990051,48.990051,54.329929,53.750050,53.750050,53.749901,53.749989,53.750000,53.749989,53.75,48.00,48.00,53.750000,48.000000,50.247181,31.999750,59.520031,53.750149,45.790058,46.508511,48.0,48.0,48.00,48.000000,52.520000,47.269878,48.00,54.680000,53.750000,56.665211,53.749950,53.750000,46.399948,41.710072,47.999851,48.000000,41.190071,47.999851,48.000000,48.000000,47.999851,53.750149,48.0,48.00000,48.000000,46.400150,53.749981,53.749981,48.00000,57.44009
2019-01-01 00:05:00,68.092598,69.269501,68.270203,68.310501,63.749329,64.000000,71.508797,71.540848,68.420021,68.529953,68.420021,67.531418,68.401917,74.887894,71.274857,74.116692,73.158730,74.930634,74.213852,73.968918,68.420021,69.151901,67.677589,68.419998,66.572327,67.704063,67.904198,68.419968,66.322372,64.939743,66.094231,67.528061,64.000000,61.922749,61.772751,61.889999,61.889999,64.000000,64.000000,61.889999,60.694931,60.709541,48.000000,52.040939,48.990051,48.990051,48.990051,54.329929,53.750050,53.750050,53.749901,53.749989,53.750000,53.749989,53.750000,48.00,48.00,53.75,48.000000,50.247181,31.999750,59.520031,53.750149,45.790058,46.508511,48.000000,48.0,48.0,48.00,52.520000,47.269878,48.000000,54.68,53.750000,56.665211,53.749950,53.750000,46.399948,41.710072,47.999851,48.000000,41.190071,47.999851,48.000000,48.000000,47.999851,53.750149,48.000000,48.0,48.00000,46.400150,53.749981,53.749981,48.000000,57.44009,53.75000
2019-01-01 00:10:00,69.269501,68.270203,68.310501,63.749329,64.000000,71.508797,71.540848,68.420021,68.529953,68.420021,67.531418,68.401917,74.887894,71.274857,74.116692,73.158730,74.930634,74.213852,73.968918,68.420021,69.151901,67.677589,68.419998,66.572327,67.704063,67.904198,68.419968,66.322372,64.939743,66.094231,67.528061,64.000000,61.922749,61.772751,61.889999,61.889999,64.000000,64.000000,61.889999,60.694931,60.709541,48.000000,52.040939,48.990051,48.990051,48.990051,54.329929,53.750050,53.750050,53.749901,53.749989,53.750000,53.749989,53.750000,48.000000,48.00,53.75,48.00,50.247181,31.999750,59.520031,53.750149,45.790058,46.508511,48.000000,48.000000,48.0,48.0,52.52,47.269878,48.000000,54.680000,53.75,56.665211,53.749950,53.750000,46.399948,41.710072,47.999851,48.000000,41.190071,47.999851,48.000000,48.000000,47.999851,53.750149,48.000000,48.000000,48.0,46.40015,53.749981,53.749981,48.000000,57.440090,53.75000,48.00000

Subset sample

In [3]:
# Randomly sample index
seed = np.random.default_rng(42)
n_samples = min(variables.FEATURE_SELECTION_SUBSAMPLE_AMOUNT, len(features))
index = seed.choice(len(features), size=n_samples, replace=False)
index.sort()

# Assign data based on sampled index
features_subset_index = features.iloc[index].to_numpy(dtype=np.float32, copy=True)
targets_subset_index = targets.iloc[index].to_numpy(dtype=np.float32, copy=True)

Core logic

Iterate over n number of features for h number of horizons

In [4]:
def mutual_info_regression_helper(item):
    return mutual_info_regression(
        features_subset_index,
        targets_subset_index[:, targets.columns.get_loc(item)],
        discrete_features="auto",
        n_neighbors=3,
        random_state=42,
    )
     
ranked_features = run_parallel(
    function=mutual_info_regression_helper,
    data=targets.columns,
)
del features_subset_index, targets_subset_index

os=windows cpu_count=8 max_assigned_workers=1

Processing..: 100%|██████████| 96/96 [01:58<00:00,  1.23s/item]

Clean up

In [5]:
features_ranked_values = pd.DataFrame(
    np.column_stack(ranked_features.copy()).astype(np.float32, copy=False),
    index=features.columns,
    columns=targets.columns,
)

features_ranked_values["mean_mi"] = features_ranked_values.mean(axis=1)
features_ranked_values.sort_values("mean_mi",ascending=False)
features_ranked_values["rank"] = np.arange(1, len(features_ranked_values) + 1)

In [6]:
features_ranked_ordered = features_ranked_values.drop(columns=["mean_mi","rank"])
features_ranked_ordered = features_ranked_ordered.rank(axis=0, ascending=False, method='min').astype(int)

View

In [7]:
display(features_ranked_values[:3])
display(features_ranked_ordered[:3])

,target_h1,target_h2,target_h3,target_h4,target_h5,target_h6,target_h7,target_h8,target_h9,target_h10,target_h11,target_h12,target_h13,target_h14,target_h15,target_h16,target_h17,target_h18,target_h19,target_h20,target_h21,target_h22,target_h23,target_h24,target_h25,target_h26,target_h27,target_h28,target_h29,target_h30,target_h31,target_h32,target_h33,target_h34,target_h35,target_h36,target_h37,target_h38,target_h39,target_h40,target_h41,target_h42,target_h43,target_h44,target_h45,target_h46,target_h47,target_h48,target_h49,target_h50,target_h51,target_h52,target_h53,target_h54,target_h55,target_h56,target_h57,target_h58,target_h59,target_h60,target_h61,target_h62,target_h63,target_h64,target_h65,target_h66,target_h67,target_h68,target_h69,target_h70,target_h71,target_h72,target_h73,target_h74,target_h75,target_h76,target_h77,target_h78,target_h79,target_h80,target_h81,target_h82,target_h83,target_h84,target_h85,target_h86,target_h87,target_h88,target_h89,target_h90,target_h91,target_h92,target_h93,target_h94,target_h95,target_h96,mean_mi,rank
nsw_price_asinh_lag_1,1.803183,1.508851,1.425775,1.274567,1.199933,1.270465,1.257572,1.147809,1.155591,0.948080,1.022517,1.071534,1.005113,0.973689,1.001190,0.991732,0.924311,0.905930,0.889194,0.780323,0.781791,0.709095,0.717773,0.714606,0.689289,0.681689,0.671475,0.591672,0.700768,0.695389,0.725609,0.732661,0.675505,0.519880,0.647360,0.560217,0.568909,0.559243,0.530430,0.619891,0.485585,0.485838,0.480301,0.471424,0.537845,0.482718,0.468375,0.475077,0.464879,0.466930,0.446911,0.546018,0.529790,0.505146,0.429002,0.435148,0.431132,0.444861,0.394920,0.395322,0.484873,0.506608,0.463839,0.385351,0.454879,0.418174,0.369057,0.551340,0.479234,0.351760,0.373829,0.350380,0.391300,0.404194,0.395407,0.430798,0.335823,0.356136,0.268979,0.370638,0.321681,0.375980,0.286000,0.390337,0.341120,0.322675,0.302459,0.349395,0.453383,0.389603,0.413827,0.370738,0.380522,0.319193,0.365897,0.339603,0.613467,1
nsw_price_asinh_lag_2,1.276056,1.317544,1.334751,1.220308,1.239410,1.131038,1.128109,1.056348,1.025346,0.848724,0.891041,0.898111,0.916419,0.868541,0.867893,0.892516,0.896286,0.811060,0.879823,0.775839,0.708220,0.598976,0.679712,0.673014,0.674660,0.711945,0.589159,0.636221,0.582914,0.618581,0.596244,0.633425,0.610874,0.518567,0.557671,0.444202,0.411584,0.504604,0.409250,0.552300,0.527413,0.404978,0.458977,0.483143,0.488775,0.441700,0.442232,0.473579,0.464128,0.447790,0.370487,0.388930,0.523310,0.516202,0.462590,0.500382,0.474365,0.436234,0.378063,0.462160,0.572712,0.558435,0.479862,0.393470,0.454566,0.404323,0.394170,0.405822,0.404735,0.334360,0.310921,0.353548,0.314242,0.326473,0.363016,0.391589,0.334449,0.341167,0.291872,0.311413,0.358742,0.392334,0.321134,0.402720,0.394084,0.250373,0.322025,0.402158,0.392992,0.359274,0.290701,0.350044,0.366183,0.255789,0.305297,0.290899,0.565923,2
nsw_price_asinh_lag_4,1.166309,1.105569,1.208324,1.047082,1.145224,1.003651,0.975733,0.979875,0.953119,0.777768,0.879207,0.720537,0.751705,0.763195,0.796970,0.773467,0.763814,0.711893,0.729307,0.650522,0.617635,0.672040,0.592826,0.588683,0.597769,0.616932,0.601327,0.606320,0.646627,0.614452,0.628191,0.595345,0.720948,0.543536,0.605496,0.524939,0.425667,0.553555,0.485752,0.511658,0.532663,0.484745,0.505065,0.493449,0.512727,0.451059,0.524062,0.459860,0.477360,0.460555,0.506452,0.429013,0.508605,0.526163,0.461269,0.479587,0.489185,0.449934,0.335554,0.463470,0.397744,0.431426,0.428239,0.366947,0.406958,0.472455,0.373998,0.387442,0.409043,0.327629,0.329119,0.417729,0.451991,0.396878,0.414416,0.437329,0.430971,0.390909,0.308912,0.307421,0.414099,0.381836,0.334882,0.405825,0.332057,0.310823,0.311108,0.412339,0.416901,0.426971,0.382548,0.416546,0.362049,0.362375,0.355506,0.375817,0.553052,3

,target_h1,target_h2,target_h3,target_h4,target_h5,target_h6,target_h7,target_h8,target_h9,target_h10,target_h11,target_h12,target_h13,target_h14,target_h15,target_h16,target_h17,target_h18,target_h19,target_h20,target_h21,target_h22,target_h23,target_h24,target_h25,target_h26,target_h27,target_h28,target_h29,target_h30,target_h31,target_h32,target_h33,target_h34,target_h35,target_h36,target_h37,target_h38,target_h39,target_h40,target_h41,target_h42,target_h43,target_h44,target_h45,target_h46,target_h47,target_h48,target_h49,target_h50,target_h51,target_h52,target_h53,target_h54,target_h55,target_h56,target_h57,target_h58,target_h59,target_h60,target_h61,target_h62,target_h63,target_h64,target_h65,target_h66,target_h67,target_h68,target_h69,target_h70,target_h71,target_h72,target_h73,target_h74,target_h75,target_h76,target_h77,target_h78,target_h79,target_h80,target_h81,target_h82,target_h83,target_h84,target_h85,target_h86,target_h87,target_h88,target_h89,target_h90,target_h91,target_h92,target_h93,target_h94,target_h95,target_h96
nsw_price_asinh_lag_1,4,4,3,5,8,1,1,5,3,1,3,2,4,1,1,1,3,2,3,3,3,1,2,1,3,7,1,8,2,2,2,1,8,15,2,1,1,4,2,3,13,15,8,15,6,5,16,8,15,11,18,2,3,12,32,17,33,26,26,46,5,8,9,34,9,17,50,1,4,42,30,60,38,26,27,19,61,30,126,34,117,64,148,29,76,42,91,92,15,50,17,34,31,67,30,58
nsw_price_asinh_lag_2,11,9,7,9,5,7,7,9,10,3,10,7,7,8,6,4,7,7,5,4,6,13,3,3,4,3,15,2,14,11,17,11,12,16,17,19,18,12,21,12,5,34,15,12,16,20,23,10,17,20,67,44,5,11,17,3,14,34,38,7,2,3,5,24,10,23,30,33,36,63,92,56,129,92,51,44,66,38,86,99,52,46,94,26,39,141,58,38,40,82,108,51,38,167,86,131
nsw_price_asinh_lag_4,13,13,12,13,13,12,13,12,11,8,12,19,20,14,13,12,17,25,16,21,18,3,18,18,16,16,11,6,4,12,9,16,1,11,9,6,14,5,8,15,4,16,2,10,8,16,4,13,9,14,6,27,7,8,18,7,10,24,85,6,25,22,17,46,37,5,47,44,32,71,68,12,13,28,18,16,14,20,61,106,16,55,76,25,91,57,74,30,24,23,30,16,43,32,45,40

Export

In [8]:
features_ranked_ordered.to_parquet(variables.FEATURES_RANKED_ORDERED)